name: cats-vs-dogs-attacker
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - pip
  - captum
  - cudatoolkit=11.0
  - foolbox
  - numpy
  - pandas
  - pytorch
  - pytorch-lightning
  - torchvision
  - pip:
    - lime
